title: Singapore Green Plan 2030
url: https://www.greenplan.gov.sg
favicon: /images/favicon.svg
colors:
  primary-color: "#00725c"
  secondary-color: "#00725c"
  media-colors:
    - title: media-color-one
      color: "#00725c"
    - title: media-color-two
      color: "#00725c"
    - title: media-color-three
      color: "#00725c"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#0d67b1"
resources_name: news
google_analytics: UA-183999332-2
shareicon: /images/sharing.jpg
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
staging: https://staging.d170y6ryrn3gwt.amplifyapp.com/
prod: https://master.d170y6ryrn3gwt.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
facebook-pixel: ""
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
