title: Singapore Green Plan 2030
url: "https://www.greenplan.gov.sg" 
favicon: /images/favicon.svg

# Site colors
colors:
  primary-color: '#00725c'
  secondary-color: '#00725c'
  media-colors:
    - title: media-color-one
      color: '#00725c'
    - title: media-color-two
      color: '#00725c'
    - title: media-color-three
      color: '#00725c'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#0d67b1'


collections:
  take-action:
    output: true
  key-focus-areas:
    output: true
resources_name: resources
google-tag-manager: UA-183999332-2
google-analytics: UA-183999332-2
shareicon: /images/sharing.jpg

description: An Isomer site of the Singapore Government

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
